### PR TITLE
Add support for uprofiler and instructions for data collection in Drupal

### PR DESCRIPTION
**Pull request by FGM**
As discussed this morning at the DC sprint.

### CODE REVIEW

**Comment by msonnabaum** [comment]
I'm not sure it's necessary to have the name Drupal anywhere in there. I dont see anything specific to it there.

I like the idea if including the sample code in the README. I usually point people to https://gist.github.com/msonnabaum/c8902d5000d892ba121b, but it makes sense to just have it here. I'd include it in the same README, under a heading like "Generating Sampling Data" or something.

And I feel like it's probably unnecessary to write out the "sample_uprofiler" file extension. Users of uprofiler are likely aware that it's an xhprof fork and won't be thrown by .sample_xhprof files.

**Comment by FGM** [comment]
New version addresses these issues.

**Comment by FGM** [comment]
Still not moving ?

**Comment by FGM** [comment]
Thanks !

2015-09-25 12:33 GMT+02:00 Mark Sonnabaum <notifications@github.com>:

**Pull request merged**
